---
name: Net-Social-Service-Facebook
version: 0.1
author:
  - 'Simon Wistow <simon@thegestalt.org>'
abstract: a Facebook plugin for Net::Social
license: unknown
requires:
  Net::Social: 0
  Test::More: 0.62
  WWW::Facebook::API: 0.4.4
provides:
  Net::Social::Service::Facebook:
    file: lib/Net/Social/Service/Facebook.pm
    version: 0.1
generated_by: Module::Build version 0.2808
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
